blog/urls.py
from django.conf.urls import url
from .views import(
	home,
	posts,
	post_editar,
	post_create,
	post_detalhe,
	sobre,
	portfolio
)

app_name = "blog"
urlpatterns = [
	url(r'^$', home, name='home' ),
	url(r'^posts/$', posts, name='posts' ),
	url(r'^posts/create/$', post_create, name='criar' ),
	url(r'^posts/(?P<id>[0-9]+)/$', post_detalhe, name='detalhe' ),
	url(r'^posts/(?P<id>[0-9]+)/editar/$', post_editar, name='editar' ),
	url(r'^sobre/$', sobre, name='sobre' ),
	url(r'^portfolio/$', portfolio.as_view(), name='portfolio' )
]

samuelgea/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('blog.urls')),
    url(r'^admin/', admin.site.urls)
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
	titulo = models.CharField( max_length=150 )
	conteudo = models.TextField()
	autor = models.ForeignKey('auth.User')
	criado = models.DateTimeField( default=timezone.now )
	atualizado = models.DateTimeField( blank=True, null=True )

	def publicar(self):
		self.save()

	def __str__(self):
		return self.titulo

class Portfolio( models.Model ):
	nome_projeto = models.CharField( max_length=100 )
	linguagens = models.CharField( max_length=250 )
	criado = models.DateTimeField( default=timezone.now )
	atualizado = models.DateTimeField( blank=True, null=True )
	link = models.CharField( max_length=250 )

	def __str__( self ):
		return self.nome_projeto

blog/forms.py
from django import forms
from .models import Post

class PostForm( forms.ModelForm ):

	class Meta:
		model = Post
		fields = ( 'titulo', 'conteudo' )

blog/views.py
from django.shortcuts import render,  redirect, get_object_or_404
from django.utils import timezone
from django.views import generic

from .models import Post, Portfolio
from .forms import PostForm

# Create your views here.
def home( request ):
	context = { 'title' : 'Blog - Samuel Antonio Gea' }
	return render( request, 'home.html', context )

def posts( request ):
	posts = Post.objects.order_by('-criado')
	context = { 'title' : 'Posts', 'posts' : posts }
	return render( request, 'posts.html', context )

def post_create( request ):
	if request.method == 'POST':
		form = PostForm( request.POST )
		if form.is_valid():
			post = form.save(commit=False)
			post.autor = request.user
			post.criado = timezone.now()
			post.save()
			return redirect('blog:posts')
	else:
		form = PostForm()
	context = { 'title' : 'Criar Post', 'form' : form }
	return render( request, 'post_create.html', context )

def sobre( request ):
	context = { 'title' : 'Sobre' }
	return render( request, 'sobre.html', context )

class portfolio( generic.ListView ):
	model = Portfolio
	template_name = "portfolio.html"
	context_object_name = "lista_projetos"

	def get_queryset( self ):
		""" RETURN ALL OBJECTOS OF Portfolio """
		return Portfolio.objects.all();


def post_detalhe( request, id ):
	post = get_object_or_404( Post, id=id)
	context = { 'title' : post.titulo, 'post' : post }
	return render( request , 'post_detalhe.html', context )

def post_editar( request, id ):
	post = get_object_or_404( Post, id=id )

	if request.method == 'POST':
		form = PostForm( request.POST, instance=post)
		if form.is_valid():
			post = form.save( commit=False )
			post.autor = request.user
			post.criado = timezone.now()
			post.save()
			return redirect('blog:posts')
	else:
		form = PostForm( instance=post )

	context = { 'title' : 'Editar Post', 'form' : form, 'post' : post }
	return render( request, 'post_editar.html', context)

blog/templates/base.html
{% load staticfiles %}
<html>

  <head>
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'blog/img/favicon.png' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/animations.css' %}" />
  </head>

  <body>

    {% include 'header.html' %}

    <div class="container-fluid">
  	{% block content %}


  	{% endblock content %}
    </div>

    {% include 'footer.html' %}

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  </body>

</html>

blog/templates/footer.html
{% load staticfiles %}
<div id="footer" class="background-azul-claro container-fluid">	

  <div class="row">

  	<footer>
	  	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

        <a href="https://plus.google.com/105282990654257770005/">
          <img src="{% static 'blog/img/googleplus.png' %}" alt="Google Plus" title="Google Plus" />
        </a>

        <a href="https://plus.google.com/105282990654257770005/">
          <img src="{% static 'blog/img/linkedin.png' %}" alt="Linkedin" title="Linkedin" />
        </a>

	    </div>
	  </footer>

  </div>	
    
  </div>
</div>

blog/templates/header.html
<div id="header" class="background-azul container-fluid">

  <div class="row">

    <header>    
      <nav class="col-lg-4 col-md-4 col-sm-6 col-xs-12 col-lg-offset-4 col-md-off-set-4 col-sm-offset-3">
        <ul class="nav nav-pills nav-justified">
          <li role="presentation"><a href="{% url 'blog:home' %}">Home</a></li>
          <li role="presentation"><a href="{% url 'blog:posts' %}">Posts</a></li>
          <li role="presentation"><a href="{% url 'blog:sobre' %}">Sobre</a></li>
          <li role="presentation"><a href="{% url 'blog:portfolio' %}">Portfolio</a></li>
        </ul>
      </nav>
    </header>

  </div>

  <div class="row">
    <div id="divisoria"></div>
  </div>
  
</div>

blog/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1">
	  
	  <h1 class="margin-top-3 text-center">Blog ~ Samuel Gea</h1>

	  <p>
	  	Sejam Bem Vindos! Nesse blog falo sobre tecnologiase frameworks. Espero que
	  	se divirta enquanto aprende. Um grande abraço.
	  <p/>

	  <h2>Linguagens Utilizadas</h2>

	  <ul class="linguagens margin-top-3">
	  	<li><img class="rotate" src="{% static 'blog/img/logo_html5.png' %}" title="Logo HTML5" alt="Logo HTML5" /></li>
	  	<li><img class="rotate" src="{% static 'blog/img/logo_java.png' %}" title="Logo Java" alt="Logo Java" /></li>
	  	<li><img class="rotate"src="{% static 'blog/img/logo_python.png' %}" title="Logo Python" alt="Logo Python" /></li>
	  	<li><img class="rotate" src="{% static 'blog/img/logo_android.png' %}" title="Logo Android" alt="Logo Android" /></li>
	  </ul>

    </div>	
  </div>

{% endblock content %}

blog/templates/portfolio.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1">

    <h1 class="text-center">Portfolio</h1>

    <table class="table table-bordered table-striped">

    	<thead>
      <tr>
        <th>Projeto</th>
        <th>Tecnologias</th>
        <th>Link</th>
      </tr>
    </thead>
    <tbody>
      {% for projeto in lista_projetos %}
        <tr>
          <td>{{ projeto.nome_projeto}}</td>
          <td>{{ projeto.linguagens }}</td>
          <td><a href="http://{{ projeto.link }}">{{ projeto.link }}</a></td>
        </tr>
      {% endfor %}
    </tbody>

    </table>

  </div>
</div>

{% endblock content %}

blog/templates/post_create.html
{% extends 'base.html' %}

{% block content %}

  <div class="row">
  	<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1">

  		<h1 class="text-center">Criar Post</h1>

  		<form class="post-form" method="POST">{% csrf_token %}
  			{{ form.as_p }}
  			<button type="submit" class="btn btn-success">Salvar</button>
  		</form>

  	</div>
  </div>

{% endblock content %}

blog/templates/post_detalhe.html
{% extends 'base.html' %}

{% block content %}

  <div class="row">
	  <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1">

      <h1 class="text-center">
        {{ post.titulo }}

        {% if user.is_authenticated %}

          <a class="btn btn-default" href="{% url 'blog:editar' id=post.id %}">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>

          <p id="logado">Logado como: {{ user.username }}</p>

        {% endif %}

      </h1>
      
      <span>{{ post.criado }}</span>

      {% if post.atualizado %}
        <span>{{ post.atualizado }}</span>
      {% endif %}

      <p>{{ post.conteudo }}</p>

	  </div>  
  </div>

{% endblock content %}

blog/templates/post_editar.html
{% extends 'base.html' %}

{% block content %}

  <div class="row">
  	<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1">

  		<h1 class="text-center">Criar Post</h1>

  		<form class="post-form" method="POST">{% csrf_token %}
  			{{ form.as_p }}
  			<button type="submit" class="btn btn-success">Salvar</button>
  		</form>

  	</div>
  </div>

{% endblock content %}

blog/templates/posts.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-lg-8 col-md-8 col-sm-10 col-xs-12 col-lg-offset-2 col-md-offset-2 col-sm-offset-1">

    <div class="posts">

      {% for post in posts %}

        <h2><a href="{% url 'blog:detalhe' id=post.id %}">{{ post.titulo }}</a></h2>

        <span>Criado: {{ post.criado }}</span>

        {% if post.atualizado %}
          <span>Atualizado: {{ post.atualizado }}</span>
        {% endif %}

        <p>{{ post.conteudo|linebreaks }}</p>

      {% endfor %}
      
    </div>

  </div>
</div>

{% endblock content %}

blog/templates/sobre.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="margin-top-5 row">

    <h1 class="display-none">Sobre - Samuel Antonio Gea</h1>

	<div class="col-lg-2 col-md-3 col-sm-6 col-xs-12 ">

      <img id="img-eu" src="{% static 'blog/img/samuelgea.jpg' %}" alt="Samuel Antonio Gea">

      <div class="text-center">
      	<h1 class="font-size-18">Samuel Antonio Gea</h1>
      	<p>Bacharel em Ciência da Computação</p>
      </div>

	</div>

	<div class="margin-10 col-lg-10 col-md-9 col-sm-6 col-xs-12">

	  <p>
	  	Primaremente sejam Bem Vindos e obriado pela visita. Criei esse blog com um propósito
	  	simples, passar o pouco que eu sei, graças a muitos blogers, canais de youtube entre outras midias
	  	que pessoas compartilhavam seu conhecimento de maneira gratuita consegui obter o conhecimento que 
	  	tenho hoje, por isso quero repassar um pouco do que foi meu passado, da mesma maneira...
	  </p>

	  <p>
	  	Abaixo vou falar um pouco sobre min, mostrar um pouco sobre meu histórico. Abraços!
	  </p>

	  <h2 class="margin-top-3">Formação</h2>

      <ul class="lista-formacao">
        <li>Técnico em Informática pelo Senac Franca</li>
        <li>Bacharel em Ciência da Computação</li>
        <li>Especialização em Gestão e Desenvolvimento de Software para Web (Cursando)</li>
      </ul>

		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


    </div>

	</div>

  </div>


{% endblock content %}

templates/base.html
{% load staticfiles %}
<html>

  <head>
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
  </head>

  <body>

    {% include 'header.html' %}

    <div class="container-fluid">
  	{% block content %}


  	{% endblock content %}
    </div>

    {% include 'footer.html' %}

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  </body>

</html>

templates/header.html
<div id="header" class="container-fluid">

  <div class="row">

    <header>    
      <nav class="col-lg-4 col-md-4 col-sm-6 col-xs-12 col-lg-offset-4 col-md-off-set-4 col-sm-offset-3">
        <ul class="nav nav-pills nav-justified">
          <li role="presentation"><a href="{% url 'blog:home' %}">Home</a></li>
          <li role="presentation"><a href="{% url 'blog:posts' %}">Posts</a></li>
          <li role="presentation"><a href="{% url 'blog:sobre' %}">Sobre</a></li>
          <li role="presentation"><a href="{% url 'blog:portfolio' %}">Portfolio</a></li>
        </ul>
      </nav>
    </header>

  </div>

  <div class="row">
    <div id="divisoria"></div>
  </div>
  
</div>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1">
	  
	  <h1 class="margin-top-3 text-center">Blog ~ Samuel Gea</h1>

	  <p>
	  	Sejam Bem Vindos! Nesse blog falo sobre tecnologiase frameworks. Espero que
	  	se divirta enquanto aprende. Um grande abraço.
	  <p/>

	  <h2>Linguagens Utilizadas</h2>

	  <ul class="linguagens margin-top-3">
	  	<li><img src="{% static 'img/logo_html5.png' %}" title="Logo HTML5" alt="Logo HTML5" /></li>
	  	<li><img src="{% static 'img/logo_java.png' %}" title="Logo Java" alt="Logo Java" /></li>
	  	<li><img src="{% static 'img/logo_python.png' %}" title="Logo Python" alt="Logo Python" /></li>
	  	<li><img src="{% static 'img/logo_android.png' %}" title="Logo Android" alt="Logo Android" /></li>
	  </ul>

    </div>	
  </div>

{% endblock content %}

templates/sobre.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="margin-top-5 row">

    <h1 class="display-none">Sobre - Samuel Antonio Gea</h1>

	<div class="col-lg-2 col-md-3 col-sm-6 col-xs-12 ">

      <img id="img-eu" src="{% static 'img/samuelgea.jpg' %}" alt="Samuel Antonio Gea">

      <div class="text-center">
      	<h1 class="font-size-18">Samuel Antonio Gea</h1>
      	<p>Bacharel em Ciência da Computação</p>
      </div>

	</div>

	<div class="margin-10 col-lg-10 col-md-9 col-sm-6 col-xs-12">

	  <p>
	  	Primaremente sejam Bem Vindos e obriado pela visita. Criei esse blog com um propósito
	  	simples, passar o pouco que eu sei, graças a muitos blogers, canais de youtube entre outras midias
	  	que pessoas compartilhavam seu conhecimento de maneira gratuita consegui obter o conhecimento que 
	  	tenho hoje, por isso quero repassar um pouco do que foi meu passado, da mesma maneira...
	  </p>

	  <p>
	  	Abaixo vou falar um pouco sobre min, mostrar um pouco sobre meu histórico. Abraços!
	  </p>

	  <h2 class="margin-top-3">Formação</h2>

      <ul class="lista-formacao">
        <li>Técnico em Informática pelo Senac Franca</li>
        <li>Bacharel em Ciência da Computação</li>
        <li>Especialização em Gestão e Desenvolvimento de Software para Web (Cursando)</li>
      </ul>

		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


    </div>

	</div>

  </div>


{% endblock content %}